config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/redxdev/ECS:
      branch: master
      repo: https://github.com/redxdev/ECS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/redxdev/ECS git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-wisteria-bat.sh
        container: qc.acc_muggy-maroon-mau
  QC.Doc:
    repos:
      github.com/redxdev/ECS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-salmon-terrier.sh
        container: qc.doc_sickly-seashell-jellyfish
      github.com/redxdev/ECS git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-bistre-coral.sh
        container: qc.doc_snappy-auburn-meerkat
      github.com/redxdev/ECS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-maroon-cow.sh
        container: qc.doc_fuzzy-jade-beaver
  QC.Lic:
    repos:
      github.com/redxdev/ECS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-fuchsia-nightingale.sh
        container: qc.lic_blurry-celadon-chin
  QC.Ver:
    repos:
      github.com/redxdev/ECS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-carmine-chinook.sh
        container: qc.ver_silly-apricot-chipmunk
timeout: 5400
