config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/redxdev/ECS:
      branch: master
      repo: https://github.com/redxdev/ECS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/redxdev/ECS git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-magenta-nightingale.sh
        container: qc.acc_stuffy-aqua-yak
  QC.Doc:
    repos:
      github.com/redxdev/ECS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-xanthic-javanese.sh
        container: qc.doc_cheeky-sangria-dachshund
      github.com/redxdev/ECS git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-amaranth-squirrel.sh
        container: qc.doc_sloppy-blue-zonkey
      github.com/redxdev/ECS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-ivory-dingo.sh
        container: qc.doc_zippy-amethyst-zonkey
  QC.Lic:
    repos:
      github.com/redxdev/ECS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-ivory-fowl.sh
        container: qc.lic_skanky-xanthic-chimpanzee
  QC.Ver:
    repos:
      github.com/redxdev/ECS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-yellow-stoat.sh
        container: qc.ver_homely-amethyst-coral
timeout: 5400
