config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/redxdev/ECS:
      branch: master
      repo: https://github.com/redxdev/ECS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/redxdev/ECS git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cerulean-indri.sh
        container: qc.acc_droopy-lime-tuatara
  QC.Doc:
    repos:
      github.com/redxdev/ECS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-pear-wildebeest.sh
        container: qc.doc_geeky-rose-harrier
      github.com/redxdev/ECS git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-peach-bat.sh
        container: qc.doc_fuzzy-peach-malamute
      github.com/redxdev/ECS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-taupe-blue.sh
        container: qc.doc_sunny-white-fowl
  QC.Lic:
    repos:
      github.com/redxdev/ECS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-peach-woodlouse.sh
        container: qc.lic_chummy-emerald-sheepdog
  QC.Sty:
    repos:
      github.com/redxdev/ECS oclint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cerise-zebu.sh
        container: qc.sty_gimpy-sepia-booby
  QC.Ver:
    repos:
      github.com/redxdev/ECS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-aqua-buffalo.sh
        container: qc.ver_sleepy-carmine-spoonbill
timeout: 5400
