config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/redxdev/ECS:
      branch: master
      repo: https://github.com/redxdev/ECS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/redxdev/ECS git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-alizarin-barnacle.sh
        container: qc.acc_randy-dandelion-gibbon
  QC.Doc:
    repos:
      github.com/redxdev/ECS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-aquamarine-cassowary.sh
        container: qc.doc_ready-flax-crane
      github.com/redxdev/ECS git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-cobalt-whale.sh
        container: qc.doc_randy-taupe-abyssinian
      github.com/redxdev/ECS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-bistre-russel.sh
        container: qc.doc_slimy-cobalt-quetzal
  QC.Lic:
    repos:
      github.com/redxdev/ECS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-cobalt-dachshund.sh
        container: qc.lic_cloudy-turquoise-vulture
  QC.Ver:
    repos:
      github.com/redxdev/ECS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-lilac-baboon.sh
        container: qc.ver_breezy-olive-seahorse
timeout: 5400
