config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/redxdev/ECS:
      branch: master
      repo: https://github.com/redxdev/ECS
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/redxdev/ECS git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-cinnamon-dolphin.sh
        container: qc.acc_silly-cerulean-rabbit
  QC.Doc:
    repos:
      github.com/redxdev/ECS find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-tomato-frigatebird.sh
        container: qc.doc_trippy-blue-caracal
      github.com/redxdev/ECS git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-fuchsia-anteater.sh
        container: qc.doc_smelly-salmon-blue
      github.com/redxdev/ECS markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-cerise-capybara.sh
        container: qc.doc_bluesy-champagne-pig
  QC.Lic:
    repos:
      github.com/redxdev/ECS licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-emerald-akita.sh
        container: qc.lic_woozy-beige-yak
  QC.Sty:
    repos:
      github.com/redxdev/ECS oclint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-indigo-serval.sh
        container: qc.sty_gummy-fuchsia-okapi
  QC.Ver:
    repos:
      github.com/redxdev/ECS get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-carmine-kudu.sh
        container: qc.ver_skimpy-chestnut-maltese
timeout: 5400
